server:
  port: 8080

spring:
  application:
    name: 03-data-modeling
  data:
    mongodb:
      uri: mongodb://localhost:27017/datamodeling_db

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG
