services:
  mongodb:
    image: mongo:7.0
    container_name: textgeo-mongodb
    ports:
      - "27017:27017"
    volumes:
      - textgeo_mongo_data:/data/db
    restart: unless-stopped

  mongo-express:
    image: mongo-express:1.0
    container_name: textgeo-mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH: "false"
    restart: unless-stopped

volumes:
  textgeo_mongo_data:
